### ISSUE TITLE
Undefined behavior: negation of -2147483648 stored in an int, trans/src/common/construct/install_fns.c:2659

### ISSUE THREAD

**Issue by pstef** [tendra/tendra#5] opened 2015-01-18 17:11 UTC
```C
		if (snatneg(value)) {
			n = -n;
		}
```

This is how tcc was started:
/home/1500100900/tendra/trunk/obj.gentoo-bootstrap/bin/tcc -Wa,-32 -Wl,-melf_i386 -c -o /home/1500100900/tendra/trunk/obj.gentoo-bootstrap/obj/tdf/src/int64/int64.o   -J/home/1500100900/tendra/trunk/obj.gentoo-bootstrap/lib/tcc/map -jc              -J/home/1500100900/tendra/trunk/obj.gentoo-bootstrap/lib/tcc/lpi -jtdfc2          -J/home/1500100900/tendra/trunk/obj.gentoo-bootstrap/lib/tcc/sys -jabi -jdep      -M -WP,-I. /home/1500100900/tendra/trunk/obj.gentoo-bootstrap/obj/tdf/src/int64/int64b.j /home/1500100900/tendra/trunk/obj.gentoo-bootstrap/obj/tdf/src/int64/abstract.j /home/1500100900/tendra/trunk/obj.gentoo-bootstrap/obj/tdf/src/int64/int64a.j

tcc itself was built with:
bmake CLANG=(which clang) BLDARCH=80x86 BLDARCHBITS=32 TCCOPTS='-Wa,-32 -Wl,-melf_i386' bootstrap

shared/mk/tendra.compiler.mk was modified as follows:
-CC:=   ${CLANG}
+CC:=   ${CLANG} -g3 -O0 -fno-optimize-sibling-calls -fno-omit-frame-pointer -fsanitize=undefined-trap -fsanitize-undefined-trap-on-error

-CCOPTS+=       -pedantic -O3
+CCOPTS+=

**Comment by katef** [comment] 2015-01-23 19:05
I believe this was caused by using `x86_64` headers whilst building `x86_32` code. Resolved by using `x32_64`.

**Comment by katef** [comment] 2015-03-28 21:22
This has two parts; the question of whether a `TDFINT` should be generated with this value in the first place (which would be an error in the int64 source), and the question of what trans ought to be doing when representing such a value.

Per my (limited) understanding of what's supposed to be happening here, the exact range of the type in trans does not matter. That is, nothing should rely on overflow.

A `TDFINT` is decoded, and (if its value fits), represented in C types in `exp.h`, where some platforms use `long` for that; others have `int`. It's possible that using `long` for all platforms would be correct. Here's a diff for that - and to change the corresponding type in the offending function to match.

````diff
Index: trans/src/common/construct/install_fns.c
===================================================================
--- trans/src/common/construct/install_fns.c    (revision 4287)
+++ trans/src/common/construct/install_fns.c    (working copy)
@@ -2417,7 +2417,7 @@
 exp
 f_make_int(variety v, signed_nat value)
 {
-   int n;
+   long n;

    if (!snat_issmall(value) ||
        (n = snatint(value), shape_size(v) > 32 &&
Index: trans/src/common/reader/exp.h
===================================================================
--- trans/src/common/reader/exp.h   (revision 4287)
+++ trans/src/common/reader/exp.h   (working copy)
@@ -45,13 +45,8 @@
 typedef union {
    struct exp_t *e;
    char *str;
-#if defined(TRANS_M68K) && !defined(tdf3)
-   long l;
-   unsigned long ui;
-#else
-   int l;
+   long int l;
    unsigned int ui;
-#endif
    float f;
    struct dec_t *glob;
````

**Comment by katef** [comment] 2015-03-30 17:38
Committed in [4298].

**Closed by katef** 2015-03-30 17:38 UTC
Labels: bug
